name: ci
on:
  push:
    branches:
      - master
  pull_request:

defaults:
  run:
    shell: bash

# Cancels a previous run if a new commit is made on the same pull request
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Bazel
      uses: bazelbuild/setup-bazel@v3
      with:
        bazel-version: 'latest'

    - name: Bazel tests
      run: bazel test src:all
